SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE pagamento;
TRUNCATE TABLE item_pedido;
TRUNCATE TABLE pedido;
TRUNCATE TABLE produto;
TRUNCATE TABLE cliente;
TRUNCATE TABLE categoria;
SET FOREIGN_KEY_CHECKS=1;
